# Generated by Django 4.2.6 on 2023-11-06 20:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0002_alter_task_description_alter_task_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='participants',
            field=models.ManyToManyField(null=True, related_name='todolist_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
