# Generated by Django 4.2.6 on 2023-11-07 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0004_alter_todolist_title_alter_todolist_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='participants',
            field=models.ManyToManyField(related_name='todolist_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
