# Generated by Django 4.2.6 on 2023-11-10 11:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0006_todolist_last_modified'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoList',
            new_name='List',
        ),
    ]
